language: node_js
node_js:
  - "9"
scripts:
  - npm install codecov -g
after_success:
  - codecov --file packages/cli-driver/coverage/coverage-final.json --root packages/cli-driver/
os:
  - linux
  - osx
cache:
  directories:
    - "node_modules"
    - $HOME/.npm