language: node_js
node_js:
  - "9"
scripts:
  - npm install codecov -g
after_success:
  - cd packages/cli-driver/ && npm run test-critical-coverage-report && codecov 
os:
  - linux
  - osx
cache:
  directories:
    - "node_modules"
    - $HOME/.npm