export const table = [
  {"sequence":"\u0000","name":"`","ctrl":true,"meta":false,"shift":false},
  {"sequence":"\u0001","name":"a","ctrl":true,"meta":false,"shift":false},
  {"sequence":"\u0002","name":"b","ctrl":true,"meta":false,"shift":false},
  {"sequence":"\u0003","name":"c","ctrl":true,"meta":false,"shift":false},
  {"sequence":"\u0004","name":"d","ctrl":true,"meta":false,"shift":false},
  {"sequence":"\u0005","name":"e","ctrl":true,"meta":false,"shift":false},
  {"sequence":"\u0006","name":"f","ctrl":true,"meta":false,"shift":false},
  {"sequence":"\u0007","name":"g","ctrl":true,"meta":false,"shift":false},
  {"sequence":"\b","name":"backspace","ctrl":false,"meta":false,"shift":false},
  {"sequence":"\t","name":"tab","ctrl":false,"meta":false,"shift":false},
  {"sequence":"\n","name":"enter","ctrl":false,"meta":false,"shift":false},
  {"sequence":"\u000b","name":"k","ctrl": true,'meta':false,'shift':false},
  {'sequence':'\f','name':'l','ctrl': true,'meta':false,'shift':false},
  {'sequence':'\r','name':'return','ctrl': false,'meta':false,'shift':false},
  {'sequence':'\u000e','name':'n','ctrl':true,'meta':false,'shift':false},
  {'sequence':'\u000f','name':'o','ctrl':true,'meta':false,'shift':false},
  {'sequence':'\u0010','name':'p','ctrl':true,'meta':false,'shift':false},
  {'sequence':'\u0011','name':'q','ctrl':true,'meta':false,'shift':false},
  {'sequence':'\u0012','name':'r','ctrl':true,'meta':false,'shift':false},
  {'sequence':'\u0013','name':'s','ctrl':true,'meta':false,'shift':false},
  {'sequence':'\u0014','name':'t','ctrl':true,'meta':false,'shift':false},
  {'sequence':'\u0015','name':'u','ctrl':true,'meta':false,'shift':false},
  {'sequence':'\u0016','name':'v','ctrl':true,'meta':false,'shift':false},
  {'sequence':'\u0017','name':'w','ctrl':true,'meta':false,'shift':false},
  {'sequence':'\u0018','name':'x','ctrl':true,'meta':false,'shift':false},
  {'sequence':'\u0019','name':'y','ctrl':true,'meta':false,'shift':false},
  {'sequence':'\u001a','name':'z','ctrl':true,'meta':false,'shift':false},
  {'sequence':'\u001b','name':'escape','ctrl':false,'meta':false,'shift':false},
  {'sequence':' ','name':'space','ctrl':false,'meta':false,'shift':false},
  {'sequence':'A','name':'a','ctrl':false,'meta':false,'shift':true},
  {'sequence':'B','name':'b','ctrl':false,'meta':false,'shift':true},
  {'sequence':'C','name':'c','ctrl':false,'meta':false,'shift':true},
  {'sequence':'D','name':'d','ctrl':false,'meta':false,'shift':true},
  {'sequence': 'E','name': 'e','ctrl': false,'meta': false,'shift': true},
  {'sequence': 'F','name': 'f','ctrl': false,'meta': false,'shift': true},
  {'sequence': 'G','name': 'g','ctrl': false,'meta': false,'shift': true},
  {'sequence': 'H','name': 'h','ctrl': false,'meta': false,'shift': true},
  {'sequence': 'I','name': 'i','ctrl': false,'meta': false,'shift': true},
  {'sequence': 'J','name': 'j','ctrl': false,'meta': false,'shift': true},
  {'sequence': 'K','name': 'k','ctrl': false,'meta': false,'shift': true},
  {'sequence': 'L','name': 'l','ctrl': false,'meta': false,'shift': true},
  {'sequence': 'M','name': 'm','ctrl': false,'meta': false,'shift': true},
  {'sequence': 'N','name': 'n','ctrl': false,'meta': false,'shift': true},
  {'sequence': 'O','name': 'o','ctrl': false,'meta': false,'shift': true},
  {'sequence': 'P','name': 'p','ctrl': false,'meta': false,'shift': true},
  {'sequence': 'Q','name': 'q','ctrl': false,'meta': false,'shift': true},
  {'sequence': 'R','name': 'r','ctrl': false,'meta': false,'shift': true},
  {'sequence': 'S','name': 's','ctrl': false,'meta': false,'shift': true},
  {'sequence': 'T','name': 't','ctrl': false,'meta': false,'shift': true},
  {'sequence': 'U','name': 'u','ctrl': false,'meta': false,'shift': true },
  { 'sequence': 'V','name': 'v','ctrl': false,'meta': false,'shift': true },
  { 'sequence': 'W','name': 'w','ctrl': false,'meta': false,'shift': true },
  { 'sequence': 'X','name': 'x','ctrl': false,'meta': false,'shift': true },
  { 'sequence': 'Y','name': 'y','ctrl': false,'meta': false,'shift': true },
  { 'sequence': 'Z','name': 'z','ctrl': false,'meta': false,'shift': true },
  { 'sequence': 'a','name': 'a','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'b','name': 'b','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'c','name': 'c','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'd','name': 'd','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'e','name': 'e','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'f','name': 'f','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'g','name': 'g','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'h','name': 'h','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'i','name': 'i','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'j','name': 'j','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'k','name': 'k','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'l','name': 'l','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'm','name': 'm','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'n','name': 'n','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'o','name': 'o','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'p','name': 'p','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'q','name': 'q','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'r','name': 'r','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 's','name': 's','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 't','name': 't','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'u','name': 'u','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'v','name': 'v','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'w','name': 'w','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'x','name': 'x','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'y','name': 'y','ctrl': false,'meta': false,'shift': false },
  { 'sequence': 'z','name': 'z','ctrl': false,'meta': false,'shift': false },
  { 'sequence': '','name': 'backspace','ctrl': false,'meta': false,'shift': false }
]
